### ISSUE TITLE
Solving building problems with `flair` and `openai-whisper` when using PyPI.

### ISSUE THREAD

**Issue by mdvdv** [expertspec/expert#12]
To install `flair` and `openai-whisper` libraries, it is highly recommended to use the following commands instead of pip install.
For `flair`:
```
pip install git+https://github.com/flairNLP/flair
```
For `openai-whisper`:
```
pip install git+https://github.com/openai/whisper.git
# To update the package:
pip install --upgrade --no-deps --force-reinstall git+https://github.com/openai/whisper.git
```

**Comment by Lameus** [comment]
The relevant versions for stable usage were chosen and can be seen in pyproject/requirements.
